const towns = [
  {
    "name": "Oneg",
    "x": 462,
    "y": 1634,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 37,
      "Leather": 34,
      "Cinnamon": 35,
      "Coffee": 43,
      "Mango": 17,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 23,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 13,
      "Saffron": 56,
      "Silk": 79
    }
  },
  {
    "name": "Nordberg",
    "x": 296,
    "y": 1455,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 31,
      "Leather": 34,
      "Cinnamon": 30,
      "Coffee": 43,
      "Mango": 15,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 20,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 11,
      "Saffron": 48,
      "Silk": 67
    }
  },
  {
    "name": "Gelbion",
    "x": 647,
    "y": 1393,
    "image": "./images/town.png",
    "goods": {
      "Sugar": 0,
      "Paprika": 0,
      "Silk": 0,
      "Mango": 0,
      "Leather": 0,
      "Nuts": 0,
      "Oil": 0,
      "Beer": 0,
      "Cinnamon": 0,
      "Rugs": 0,
      "Tobacco": 0,
      "Pepper": 0,
      "Wine": 0,
      "Grog": 0,
      "Saffron": 0,
      "Salt": 0,
      "Dates": 0,
      "Coffee": 0,
      "Vanilla": 0,
      "Pineapples": 0
    }
  },
  {
    "name": "Corsa-Nois",
    "x": 897,
    "y": 1671,
    "image": "./images/pirate.png",
    "goods": {
      "Sugar": 0,
      "Paprika": 0,
      "Silk": 0,
      "Mango": 0,
      "Leather": 0,
      "Nuts": 0,
      "Oil": 0,
      "Beer": 0,
      "Cinnamon": 0,
      "Rugs": 0,
      "Tobacco": 0,
      "Pepper": 0,
      "Wine": 0,
      "Grog": 0,
      "Saffron": 0,
      "Salt": 0,
      "Dates": 0,
      "Coffee": 0,
      "Vanilla": 0,
      "Pineapples": 0
    }
  },
  {
    "name": "Nisogora",
    "x": 222,
    "y": 1297,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 28,
      "Leather": 34,
      "Cinnamon": 27,
      "Coffee": 16,
      "Mango": 13,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 18,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 10,
      "Saffron": 43,
      "Silk": 60
    }
  },
  {
    "name": "Cursed city",
    "x": 145,
    "y": 1065,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 37,
      "Wine": 11,
      "Grog": 11,
      "Rugs": 24,
      "Leather": 34,
      "Cinnamon": 23,
      "Coffee": 42,
      "Mango": 11,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 15,
      "Pepper": 36,
      "Beer": 6,
      "Sugar": 51,
      "Salt": 21,
      "Tobacco": 54,
      "Dates": 8,
      "Saffron": 37,
      "Silk": 52
    }
  },
  {
    "name": "Naabad Stronghold",
    "x": 551,
    "y": 1019,
    "image": "./images/pirate.png",
    "goods": {
      "Sugar": 0,
      "Paprika": 0,
      "Silk": 0,
      "Mango": 0,
      "Leather": 0,
      "Nuts": 0,
      "Oil": 0,
      "Beer": 0,
      "Cinnamon": 0,
      "Rugs": 0,
      "Tobacco": 0,
      "Pepper": 0,
      "Wine": 0,
      "Grog": 0,
      "Saffron": 0,
      "Salt": 0,
      "Dates": 0,
      "Coffee": 0,
      "Vanilla": 0,
      "Pineapples": 0
    }
  },
  {
    "name": "West Bastion",
    "x": 273,
    "y": 828,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 16,
      "Vanilla": 32,
      "Wine": 12,
      "Grog": 12,
      "Rugs": 24,
      "Leather": 29,
      "Cinnamon": 23,
      "Coffee": 36,
      "Mango": 11,
      "Oil": 19,
      "Nuts": 13,
      "Paprika": 15,
      "Pepper": 30,
      "Beer": 7,
      "Sugar": 43,
      "Salt": 24,
      "Tobacco": 46,
      "Dates": 8,
      "Saffron": 37,
      "Silk": 52
    }
  },
  {
    "name": "Masadora",
    "x": 662,
    "y": 823,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 15,
      "Vanilla": 29,
      "Wine": 14,
      "Grog": 14,
      "Rugs": 24,
      "Leather": 26,
      "Cinnamon": 23,
      "Coffee": 32,
      "Mango": 11,
      "Oil": 17,
      "Nuts": 12,
      "Paprika": 15,
      "Pepper": 15,
      "Beer": 8,
      "Sugar": 39,
      "Salt": 27,
      "Tobacco": 41,
      "Dates": 8,
      "Saffron": 37,
      "Silk": 52
    }
  },
  {
    "name": "Sharhat",
    "x": 391,
    "y": 506,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 14,
      "Vanilla": 27,
      "Wine": 15,
      "Grog": 15,
      "Rugs": 24,
      "Leather": 24,
      "Cinnamon": 23,
      "Coffee": 30,
      "Mango": 11,
      "Oil": 16,
      "Nuts": 11,
      "Paprika": 15,
      "Pepper": 25,
      "Beer": 9,
      "Sugar": 36,
      "Salt": 30,
      "Tobacco": 38,
      "Dates": 8,
      "Saffron": 37,
      "Silk": 52
    }
  },
  {
    "name": "Devious",
    "x": 714,
    "y": 428,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 29,
      "Leather": 20,
      "Cinnamon": 28,
      "Coffee": 25,
      "Mango": 14,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 18,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 10,
      "Saffron": 44,
      "Silk": 62
    }
  },
  {
    "name": "El Tigre",
    "x": 744,
    "y": 205,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 32,
      "Leather": 20,
      "Cinnamon": 30,
      "Coffee": 25,
      "Mango": 15,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 20,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 11,
      "Saffron": 48,
      "Silk": 68
    }
  },
  {
    "name": "Al-Khalif",
    "x": 135,
    "y": 177,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 13,
      "Vanilla": 31,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 24,
      "Leather": 28,
      "Cinnamon": 23,
      "Coffee": 35,
      "Mango": 11,
      "Oil": 18,
      "Nuts": 13,
      "Paprika": 15,
      "Pepper": 29,
      "Beer": 9,
      "Sugar": 42,
      "Salt": 31,
      "Tobacco": 44,
      "Dates": 8,
      "Saffron": 37,
      "Silk": 52
    }
  },
  {
    "name": "San Cristobel",
    "x": 1010,
    "y": 227,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 36,
      "Leather": 20,
      "Cinnamon": 34,
      "Coffee": 25,
      "Mango": 17,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 22,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 12,
      "Saffron": 55,
      "Silk": 76
    }
  },
  {
    "name": "Pirate City",
    "x": 1132,
    "y": 142,
    "image": "./images/pirate.png",
    "goods": {
      "Sugar": 0,
      "Paprika": 0,
      "Silk": 0,
      "Mango": 0,
      "Leather": 0,
      "Nuts": 0,
      "Oil": 0,
      "Beer": 0,
      "Cinnamon": 0,
      "Rugs": 0,
      "Tobacco": 0,
      "Pepper": 0,
      "Wine": 0,
      "Grog": 0,
      "Saffron": 0,
      "Salt": 0,
      "Dates": 0,
      "Coffee": 0,
      "Vanilla": 0,
      "Pineapples": 0
    }
  },
  {
    "name": "San Martinas",
    "x": 1455,
    "y": 194,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 41,
      "Leather": 20,
      "Cinnamon": 39,
      "Coffee": 25,
      "Mango": 19,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 26,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "South Bastion",
    "x": 1740,
    "y": 301,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 41,
      "Leather": 20,
      "Cinnamon": 39,
      "Coffee": 25,
      "Mango": 19,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 26,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Bord Radel",
    "x": 2051,
    "y": 173,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 41,
      "Leather": 20,
      "Cinnamon": 39,
      "Coffee": 25,
      "Mango": 19,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 26,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Puerto Salada",
    "x": 2342,
    "y": 374,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 41,
      "Leather": 20,
      "Cinnamon": 39,
      "Coffee": 25,
      "Mango": 19,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 26,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Los Catuano",
    "x": 2093,
    "y": 425,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 41,
      "Leather": 20,
      "Cinnamon": 39,
      "Coffee": 25,
      "Mango": 19,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 26,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Santa Maria",
    "x": 2290,
    "y": 592,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 11,
      "Vanilla": 22,
      "Wine": 15,
      "Grog": 15,
      "Rugs": 41,
      "Leather": 20,
      "Cinnamon": 39,
      "Coffee": 25,
      "Mango": 19,
      "Oil": 13,
      "Nuts": 9,
      "Paprika": 26,
      "Pepper": 21,
      "Beer": 9,
      "Sugar": 30,
      "Salt": 30,
      "Tobacco": 32,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "St Jean",
    "x": 1851,
    "y": 612,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 14,
      "Vanilla": 27,
      "Wine": 15,
      "Grog": 15,
      "Rugs": 41,
      "Leather": 24,
      "Cinnamon": 39,
      "Coffee": 30,
      "Mango": 19,
      "Oil": 16,
      "Nuts": 11,
      "Paprika": 26,
      "Pepper": 25,
      "Beer": 8,
      "Sugar": 36,
      "Salt": 29,
      "Tobacco": 38,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Freebooter Bay",
    "x": 2378,
    "y": 814,
    "image": "./images/pirate.png",
    "goods": {
      "Sugar": 0,
      "Paprika": 0,
      "Silk": 0,
      "Mango": 0,
      "Leather": 0,
      "Nuts": 0,
      "Oil": 0,
      "Beer": 0,
      "Cinnamon": 0,
      "Rugs": 0,
      "Tobacco": 0,
      "Pepper": 0,
      "Wine": 0,
      "Grog": 0,
      "Saffron": 0,
      "Salt": 0,
      "Dates": 0,
      "Coffee": 0,
      "Vanilla": 0,
      "Pineapples": 0
    }
  },
  {
    "name": "Fiji",
    "x": 1957,
    "y": 927,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 15,
      "Vanilla": 29,
      "Wine": 12,
      "Grog": 12,
      "Rugs": 41,
      "Leather": 27,
      "Cinnamon": 39,
      "Coffee": 33,
      "Mango": 19,
      "Oil": 17,
      "Nuts": 12,
      "Paprika": 26,
      "Pepper": 28,
      "Beer": 7,
      "Sugar": 40,
      "Salt": 24,
      "Tobacco": 42,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Brandport",
    "x": 2206,
    "y": 1029,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 15,
      "Vanilla": 29,
      "Wine": 12,
      "Grog": 12,
      "Rugs": 41,
      "Leather": 26,
      "Cinnamon": 39,
      "Coffee": 33,
      "Mango": 19,
      "Oil": 17,
      "Nuts": 12,
      "Paprika": 26,
      "Pepper": 28,
      "Beer": 7,
      "Sugar": 39,
      "Salt": 23,
      "Tobacco": 42,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Freedom Bay",
    "x": 2383,
    "y": 1205,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 17,
      "Vanilla": 33,
      "Wine": 11,
      "Grog": 11,
      "Rugs": 41,
      "Leather": 30,
      "Cinnamon": 39,
      "Coffee": 37,
      "Mango": 19,
      "Oil": 19,
      "Nuts": 14,
      "Paprika": 26,
      "Pepper": 31,
      "Beer": 6,
      "Sugar": 44,
      "Salt": 22,
      "Tobacco": 47,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "North Bastion",
    "x": 2079,
    "y": 1385,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 37,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 41,
      "Leather": 34,
      "Cinnamon": 39,
      "Coffee": 42,
      "Mango": 19,
      "Oil": 22,
      "Nuts": 15,
      "Paprika": 26,
      "Pepper": 35,
      "Beer": 5,
      "Sugar": 50,
      "Salt": 18,
      "Tobacco": 54,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Northside",
    "x": 2302,
    "y": 1554,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 41,
      "Leather": 34,
      "Cinnamon": 39,
      "Coffee": 43,
      "Mango": 19,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 26,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Severoangelsk",
    "x": 1965,
    "y": 1600,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 41,
      "Leather": 34,
      "Cinnamon": 39,
      "Coffee": 43,
      "Mango": 19,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 26,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Aldansk",
    "x": 1737,
    "y": 1640,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 41,
      "Leather": 34,
      "Cinnamon": 39,
      "Coffee": 43,
      "Mango": 19,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 26,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Everston",
    "x": 1177,
    "y": 1533,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 39,
      "Leather": 34,
      "Cinnamon": 37,
      "Coffee": 43,
      "Mango": 18,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 25,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 13,
      "Saffron": 60,
      "Silk": 84
    }
  },
  {
    "name": "Aruba",
    "x": 1461,
    "y": 1383,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 41,
      "Leather": 34,
      "Cinnamon": 39,
      "Coffee": 43,
      "Mango": 19,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 26,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Surako",
    "x": 747,
    "y": 1189,
    "image": "./images/freeport.png",
    "goods": {
      "Pineapples": 18,
      "Vanilla": 36,
      "Wine": 12,
      "Grog": 12,
      "Rugs": 28,
      "Leather": 33,
      "Cinnamon": 27,
      "Coffee": 41,
      "Mango": 13,
      "Oil": 21,
      "Nuts": 15,
      "Paprika": 18,
      "Pepper": 34,
      "Beer": 7,
      "Sugar": 49,
      "Salt": 24,
      "Tobacco": 52,
      "Dates": 10,
      "Saffron": 43,
      "Silk": 60
    }
  },
  {
    "name": "Nevis",
    "x": 1107,
    "y": 1163,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 37,
      "Wine": 12,
      "Grog": 12,
      "Rugs": 33,
      "Leather": 34,
      "Cinnamon": 32,
      "Coffee": 42,
      "Mango": 16,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 21,
      "Pepper": 36,
      "Beer": 7,
      "Sugar": 51,
      "Salt": 23,
      "Tobacco": 54,
      "Dates": 11,
      "Saffron": 51,
      "Silk": 71
    }
  },
  {
    "name": "Bridgetown",
    "x": 984,
    "y": 832,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 15,
      "Vanilla": 29,
      "Wine": 14,
      "Grog": 14,
      "Rugs": 28,
      "Leather": 27,
      "Cinnamon": 27,
      "Coffee": 33,
      "Mango": 13,
      "Oil": 18,
      "Nuts": 12,
      "Paprika": 18,
      "Pepper": 28,
      "Beer": 8,
      "Sugar": 40,
      "Salt": 28,
      "Tobacco": 43,
      "Dates": 10,
      "Saffron": 43,
      "Silk": 61
    }
  },
  {
    "name": "Charleston",
    "x": 1031,
    "y": 658,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 14,
      "Vanilla": 27,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 30,
      "Leather": 25,
      "Cinnamon": 29,
      "Coffee": 31,
      "Mango": 14,
      "Oil": 16,
      "Nuts": 11,
      "Paprika": 19,
      "Pepper": 26,
      "Beer": 9,
      "Sugar": 37,
      "Salt": 31,
      "Tobacco": 39,
      "Dates": 10,
      "Saffron": 46,
      "Silk": 64
    }
  },
  {
    "name": "Laguana Blanco",
    "x": 1310,
    "y": 663,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 15,
      "Vanilla": 30,
      "Wine": 15,
      "Grog": 15,
      "Rugs": 35,
      "Leather": 28,
      "Cinnamon": 33,
      "Coffee": 34,
      "Mango": 16,
      "Oil": 18,
      "Nuts": 13,
      "Paprika": 22,
      "Pepper": 29,
      "Beer": 8,
      "Sugar": 41,
      "Salt": 29,
      "Tobacco": 44,
      "Dates": 12,
      "Saffron": 53,
      "Silk": 75
    }
  },
  {
    "name": "La Navidad",
    "x": 1668,
    "y": 711,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 15,
      "Vanilla": 29,
      "Wine": 14,
      "Grog": 14,
      "Rugs": 41,
      "Leather": 26,
      "Cinnamon": 39,
      "Coffee": 33,
      "Mango": 19,
      "Oil": 17,
      "Nuts": 12,
      "Paprika": 26,
      "Pepper": 28,
      "Beer": 8,
      "Sugar": 39,
      "Salt": 27,
      "Tobacco": 42,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Tortuga",
    "x": 1521,
    "y": 900,
    "image": "./images/pirate.png",
    "goods": {
      "Sugar": 0,
      "Paprika": 0,
      "Silk": 0,
      "Mango": 0,
      "Leather": 0,
      "Nuts": 0,
      "Oil": 0,
      "Beer": 0,
      "Cinnamon": 0,
      "Rugs": 0,
      "Tobacco": 0,
      "Pepper": 0,
      "Wine": 0,
      "Grog": 0,
      "Saffron": 0,
      "Salt": 0,
      "Dates": 0,
      "Coffee": 0,
      "Vanilla": 0,
      "Pineapples": 0
    }
  },
  {
    "name": "Thermopylae",
    "x": 1720,
    "y": 1043,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 18,
      "Vanilla": 35,
      "Wine": 11,
      "Grog": 11,
      "Rugs": 41,
      "Leather": 32,
      "Cinnamon": 39,
      "Coffee": 40,
      "Mango": 19,
      "Oil": 21,
      "Nuts": 15,
      "Paprika": 26,
      "Pepper": 33,
      "Beer": 6,
      "Sugar": 47,
      "Salt": 21,
      "Tobacco": 50,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Gray Island",
    "x": 1798,
    "y": 1329,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 19,
      "Vanilla": 38,
      "Wine": 9,
      "Grog": 9,
      "Rugs": 41,
      "Leather": 34,
      "Cinnamon": 39,
      "Coffee": 43,
      "Mango": 19,
      "Oil": 22,
      "Nuts": 16,
      "Paprika": 26,
      "Pepper": 36,
      "Beer": 5,
      "Sugar": 51,
      "Salt": 18,
      "Tobacco": 55,
      "Dates": 14,
      "Saffron": 63,
      "Silk": 88
    }
  },
  {
    "name": "Assab",
    "x": 126,
    "y": 391,
    "image": "./images/town.png",
    "goods": {
      "Pineapples": 16,
      "Vanilla": 31,
      "Wine": 16,
      "Grog": 16,
      "Rugs": 24,
      "Leather": 28,
      "Cinnamon": 23,
      "Coffee": 35,
      "Mango": 11,
      "Oil": 18,
      "Nuts": 13,
      "Paprika": 15,
      "Pepper": 29,
      "Beer": 9,
      "Sugar": 42,
      "Salt": 31,
      "Tobacco": 32,
      "Dates": 8,
      "Saffron": 37,
      "Silk": 52
    }
  }
]




// export
export default towns;